server:
  servlet:
    context-path: /
  port: 8080
spring:
  application:
    name: datatochain
  profiles:
    active: local
  # 强制指定响应头content-type是utf-8编码
  http:
    encoding:
      force: true

swagger:
  base-package: io.nuls.data

logging:
  level:
    io.nuls.data.dao: debug
mybatis:
configuration:
log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# actuator 监控配置
management:
  endpoints:
    web:
      exposure:
        #默认值访问health,info端点  用*可以包含全部端点
        include: "*"
      #修改访问路径 2.0之前默认是/; 2.0默认是/actuator可以通过这个属性值修改
      base-path: /actuator


